name: flutter_rentaza
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  material_design_icons_flutter: ^3.2.4096
  image: ^2.1.4
  multi_image_picker: ^4.5.5
  http: ^0.12.0+2
  cached_network_image: ^1.1.1
  rxdart: ^0.22.0
  global_configuration: ^1.1.0
  firebase_messaging: ^5.1.5
  shared_preferences: ^0.5.2
  modal_progress_hud: ^0.1.3
  # AndroidX Support
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3
  google_sign_in: ^4.0.7
  share: ^0.6.1
  flutter_staggered_grid_view: ^0.3.0
  webview_flutter: 0.3.14+1
  # flutter_webview_plugin: ^0.3.4
  flutter_launcher_icons: ^0.7.0
  flutter_html: ^0.9.6
  flutter_tags: ^0.4.3
  charts_flutter: ^0.6.0
  image_crop: ^0.3.1
  carousel_slider: ^1.3.1
  uuid: ^2.0.0
  intl: ^0.16.0
  transparent_image: ^0.1.0
  flutter_image_compress: ^0.6.3
  simple_logger: ^1.5.1+1
  flushbar: ^1.9.0
  fluttertoast: ^3.1.3
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  #  speech_recognition: ^0.3.0
  photo_view: ^0.5.0
  flutter_local_notifications: ^0.8.2
  shipping_plugin:
    git:
      url: git://github.com/dongdm6897/flutter_shipping_plugin
      ref: 1.0.0

dependency_overrides:
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/no_data.png
    - assets/images/no_image.png
    - assets/images/banner.png
    - assets/images/logo_b2.png
    - assets/images/default_avatar.png
    - assets/images/thingstosell.jpg
    - assets/images/social/flogo.png
    - assets/images/social/glogo.png
    - assets/images/bg-summer.jpg
    - assets/images/logo.png
    - assets/images/order_flow.png
    - assets/json/notification.json
    - assets/json/product.json
    - assets/json/brand.json
    - assets/json/ranking.json
    - assets/json/messages.json
    - assets/json/category.json
    - assets/json/collection.json
    - assets/cfg/app_settings.json
    - assets/json/users.json
    - assets/json/app.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
